version: 1.0.{build}

nuget:

  account_feed: true

  project_feed: true

build:

  publish_wap: true

  verbosity: minimal

deploy:

- provider: GitHub

  auth_token:

    secure: pFOBijzWDiDlSAG2HEfnrOFBR7O9rSheUCu1M5OYxsqbE9fvjMYlGftzm/4nSB+Q

  draft: true

  force_update: true

  on:

    branch: master

- provider: Webhook

  url: https://ci.appveyor.com/api/github/webhook?id=gpsfxl0lrdbvrx2c

  authorization:

    secure: z2sd0370wxO+t/gRF784cS54pWRivvyoanu5PM3JniM=

notifications:

- provider: Email

  to:

  - admin@dslbd.online

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: false
